version: "3.8"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: password
    restart: always
    networks:
      - nesjs-network
    ports:
      - "3306:3306"
    expose:
      - "3306"

  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: ./api
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app/api
      - /usr/src/app/api/node_modules
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql

  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: ./api
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app/api
      - /usr/src/app/api/node_modules
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql

networks:
  nesjs-network:
